name: .NET

on:
  push:
    branches:
      - dev  

defaults:
  run:
    working-directory: ../HackathonFiap.Lambda.Relatorio

jobs:
  build:

    runs-on: ubuntu-latest
    env:      
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      region: us-east-2

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools      
      - name: Deploy to Lambda        
        run: dotnet lambda deploy-function --region us-east-2 --function-name hackaton-lambda-relatorio -pl HackathonFiap.Lambda.Relatorio
        